### PR TITLE
updating gitignore

### PR DESCRIPTION
**Pull request by JonathanTech**
updating to hide .ruby-gemset files
nothing major, just cleanup since it was marking my unmodified repo as changed because it was tracking this file

### CODE REVIEW

**Comment by lorneliechty** [comment]
Such a controversial first PR!! :scream: 

:ship:

**Comment by txssseal** [comment]
:+1:

**Comment by bbean86** [comment]
:ship:

**Comment by jspies** [comment]
@JonathanTech please merge

**Comment by teubanks** [comment]
:shipit:

**Comment by jspies** [comment]
:shipit:

**Comment by jspies** [comment]
and install trailer

**Comment by bbean86** [comment]
:ship:

**Comment by teubanks** [comment]
Looks good 
:+1:

**Comment by jspies** [comment]
wait..... I have a concern. j/l lol :ship:

**Pull request merged**
